Develop
alexandrlonski/server pull request #1
Opened 2021-12-01 09:56 UTC by alexandrlonski

![cinema_DB](https://user-images.githubusercontent.com/57103844/144212078-c405374c-1361-4e97-84c3-a8b757298019.PNG)
I created a database, connected to it and added tables

2021-12-05 07:13 UTC, yavorovsky requested changes

2021-12-05 07:13 UTC, yavorovsky commented on .env
> +SECRET_KEY=sekret_key_321
.env file should be ignored, here is a secure information

2021-12-05 07:13 UTC, yavorovsky commented on controllers/userController.js
> +class UserController {
Why do you need the class here if you use it once and have no usage "this" here ??

2021-12-05 07:13 UTC, yavorovsky commented on middleware/ErrorHandlingMiddleware.js
> +const ApiError = require("../error/ApiError");
How about adding "logger"? If you run the server constantly and something was broken a week ago, how would you detect it?

2021-12-05 07:13 UTC, yavorovsky commented on middleware/ErrorHandlingMiddleware.js
> +const ApiError = require("../error/ApiError");
Take a look at "morgan" and stuff like this

2021-12-05 07:13 UTC, yavorovsky commented on controllers/userController.js
> +      return next(ApiError.internal("Wrong password"));
Maybe would rather have a file with constants for messages?

2021-12-05 07:13 UTC, yavorovsky commented on controllers/userController.js
> +    const hashPassword = await bcrypt.hash(password, 5);
hash info (5 in this case) and etc. should be hidden in .env file

2021-12-05 07:13 UTC, yavorovsky commented on error/ApiError.js
> +  static badRequest(message) {
Nice approach 👍

2021-12-05 07:13 UTC, yavorovsky commented on error/ApiError.js
> +    return new ApiError(404, message);
Take a look at https://www.npmjs.com/package/http-status-codes

2021-12-05 07:13 UTC, yavorovsky commented on index.js
> +    app.listen(PORT, () => console.log(`Server started omn port ${PORT}`));
on*

2021-12-05 07:13 UTC, yavorovsky commented on middleware/checkRoleMiddleware.js
> +
why checkRoleMiddleware duplicates authMiddleware ?

2021-12-06 12:39 UTC, alexandrlonski commented on index.js
> +    app.listen(PORT, () => console.log(`Server started omn port ${PORT}`));
fixed

2021-12-06 12:39 UTC, alexandrlonski commented on .env
> +SECRET_KEY=sekret_key_321
fixed

2021-12-06 12:43 UTC, alexandrlonski commented on controllers/userController.js
> +    const hashPassword = await bcrypt.hash(password, 5);
+

2021-12-06 12:43 UTC, alexandrlonski commented on middleware/checkRoleMiddleware.js
> +
fixed

2021-12-29 10:05 UTC, alexandrlonski commented on controllers/userController.js
> +class UserController {
+

2021-12-29 10:06 UTC, alexandrlonski commented on controllers/userController.js
> +      return next(ApiError.internal("Wrong password"));
+

2021-12-29 10:06 UTC, alexandrlonski commented on error/ApiError.js
> +    return new ApiError(404, message);
+

2021-12-29 10:09 UTC, merged